# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
kotlin = "2.4.20"
kotlinxDatetime = "0.8.0"
kotlinxSerializationJSON = "1.11.0"
kotlinxCoroutines = "1.10.2"
ioNetty = "4.2.18.Final"
hopliteYaml = "2.9.0"
bctls = "1.86.1"
bcpkix = "1.86"

[libraries]
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJSON" }
kotlinxCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
ioNetty = { module = "io.netty:netty-all", version.ref = "ioNetty" }
hopliteYaml = { module = "com.sksamuel.hoplite:hoplite-yaml", version.ref = "hopliteYaml" }
bctls = { module = "org.bouncycastle:bctls-jdk18on", version.ref = "bctls" }
bcpkix = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bcpkix" }

# Libraries can be bundled together for easier import
[bundles]
kotlinxEcosystem = ["kotlinxDatetime", "kotlinxSerialization", "kotlinxCoroutines"]

[plugins]
kotlinPluginSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
