package org.givashot.tls.constant

const val TLS_RECORD_HEADER_LENGTH = 5

// 2^14 + 256
const val TLS_MAX_RECORD_SIZE = (1 shl 14) + 256

const val TLS_HANDSHAKE_CONTENT_TYPE = 0x16
const val TLS_APPLICATION_DATA_CONTENT_TYPE = 0x17
const val TLS_RECORD_VERSION_HIGH = 3
const val TLS_RECORD_VERSION_LOW = 3
const val TLS_AEAD_TAG_LENGTH = 16

const val TLS_HANDSHAKE_MAX_CLIENT_HELLO_LENGTH = 64 * 1024
const val TLS_HANDSHAKE_HEADER_LENGTH = 4
const val TLS_HANDSHAKE_CLIENT_HELLO_CONTENT_TYPE = 1
const val TLS_HANDSHAKE_SERVER_HELLO_CONTENT_TYPE = 2
const val TLS_HANDSHAKE_ENCRYPTED_EXTENSIONS_CONTENT_TYPE = 8
const val TLS_HANDSHAKE_CERTIFICATE_CONTENT_TYPE = 11
const val TLS_HANDSHAKE_CERTIFICATE_VERIFY_CONTENT_TYPE = 15
const val TLS_HANDSHAKE_FINISH_CONTENT_TYPE = 20


